markdown: redcarpet
pygments: true
permalink: /blog/:year/:month/:day/:title/
destination: public
source: source
name: Greg Karékinian
url: http://karekinian.com
description: Insert witty subtitle here.
twitter: gregkare
github: gregkare
category_dir: blog/categories
category_title_prefix: "Category: "
