markdown: HTMLPipeline
permalink: /blog/:year/:month/:day/:title/
destination: public
source: source
name: Greg Karékinian
title: Greg Karékinian
email: greg [AT] karekinian [DOT] com
url: https://karekinian.com
baseurl: ""
description: Insert witty subtitle here.
username: gregkare
category_dir: blog/categories
category_title_prefix: "Category: "
gems:
  - jekyll-html-pipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "emojifilter"
    - "syntaxhighlightfilter"

  context:
    asset_root: "/images"
    gfm: false
